export const PTZ_CAPABILITIES_DETECTED = 'PTZ_CAPABILITIES_DETECTED';
export const PTZ_RESET = 'PTZ_RESET';
export const PTZ_COMMAND_PENDING = 'PTZ_COMMAND_PENDING';
export const PTZ_COMMAND_SUCCEEDED = 'PTZ_COMMAND_SUCCEEDED';
export const PTZ_COMMAND_FAILED = 'PTZ_COMMAND_FAILED';
export const PTZ_SET_PANEL_VISIBLE = 'PTZ_SET_PANEL_VISIBLE';
